SET SERVEROUTPUT ON;

CREATE TABLE EMP (
Empno NUMBER,
Ename VARCHAR2(50),
Salary NUMBER
);

CREATE TABLE NEWEMP (
Empno NUMBER,
Ename VARCHAR2(50),
Salary NUMBER
);

INSERT INTO EMP VALUES (101, 'John', 40000);
INSERT INTO EMP VALUES (102, 'Alice', 50000);

COMMIT;

CREATE OR REPLACE TRIGGER backup_deleted_emp
BEFORE DELETE ON EMP
FOR EACH ROW
BEGIN
INSERT INTO NEWEMP (Empno, Ename, Salary)
VALUES (:OLD.Empno, :OLD.Ename, :OLD.Salary);
END;


/
DELETE FROM EMP WHERE Empno = 101;

COMMIT;

SELECT * FROM NEWEMP;

“ OUTPUT RESUIT”
EMPNO ENAME SALARY
----------------------
101 John 40000