 SET SERVEROUTPUT ON;

CREATE TABLE EMP (
Empno NUMBER,
Ename VARCHAR2(50),
Salary NUMBER
);

CREATE TABLE NEWEMP (
Empno NUMBER,
Ename VARCHAR2(50),
Salary NUMBER
);
CREATE OR REPLACE TRIGGER insert_into_newemp
AFTER INSERT ON EMP
FOR EACH ROW
BEGIN
INSERT INTO NEWEMP (Empno, Ename, Salary)
VALUES (:NEW.Empno, :NEW.Ename, :NEW.Salary);
END;
/

INSERT INTO EMP VALUES (101, 'John', 40000);
INSERT INTO EMP VALUES (102, 'Alice', 50000);

COMMIT;

SELECT * FROM NEWEMP;

“ OUTPUT RESUIT”
EMPNO ENAME SALARY
----------------------
101 John 40000
102 Alice 50000