SET SERVEROUTPUT ON;

CREATE TABLE EMP (
Empno NUMBER,
Ename VARCHAR2(50),
Salary NUMBER
);

CREATE OR REPLACE TRIGGER check_salary
BEFORE INSERT ON EMP
FOR EACH ROW
BEGIN
IF :NEW.Salary > 50000 THEN
:NEW.Salary := 50000;
END IF;
END;
/

INSERT INTO EMP VALUES (101, 'John', 40000);
INSERT INTO EMP VALUES (102, 'Alice', 60000);

COMMIT;

SELECT * FROM EMP;

“OUTPUT RESUIT”
EMPNO ENAME SALARY
----------------------
101 John 40000
102 Alice 50000